img_classifier: output/mnist_classifier_pretrain_resnet_rotation/img_classifier.pt
ae: output/mnist_ae_nogan_baseline/ae.pt
start_option: random
stop_option: flip
add_real_cls_vec: false
force_hardcode: true
only_recon: true
inject_z: false
add_gan: false
use_patch_gan_dis: true
num_iters: 500
max_iters: 50000
extra_layers: 0
lr: 0.001
min_chg_lambda: 1.0
cls_lambda: 1.0
img_size: 32
depth: 4
n_disc_layers: 3
output_dir: output
exp_name: mnist_cf_random_analyze_baseline
num_features: 64
font_size: 10
root_dset: data