use_bbox: true
continue_checkpoint: false
no_scheduler: true
img_classifier: output/cub_img_classifier_small/img_classifier.pt
add_real_cls_vec: false
force_hardcode: false
only_recon: true
add_gan: true
inject_z: true
batch_size: 64
epochs: 5000
extra_layers: 0
lr: 0.0002
recon_lambda: 1.0
recon_zero_lambda: 0
cls_lambda: 0
cls_zero_lambda: 0
kl_lambda: 0.001
img_size: 64
depth: 5
gamma: 10
sparcity_lambda: 0
force_dis_lambda: 0
pixel_loss: l1
output_dir: output
exp_name: cub_ae_512_only_recon_add_gan_bn_interpolate_dense_up_reg_mlr_g2_inject_z_nomap_kl
num_features: 512
root_dset: /local/scratch/cv_datasets/CUB_200_2011/