continue_checkpoint: true
no_scheduler: true
img_classifier: output/mnist_classifier_baseline/img_classifier.pt
add_real_cls_vec: false
force_hardcode: false
only_recon: true
add_gan: true
use_patch_gan_dis: true
apply_rotation: false
batch_size: 128
epochs: 20
extra_layers: 0
lr: 0.0002
recon_lambda: 1.0
recon_zero_lambda: 0
cls_lambda: 0
cls_zero_lambda: 0
kl_lambda: 0.001
img_size: 32
depth: 4
n_disc_layers: 3
gamma: 6.2
sparcity_lambda: 0
force_dis_lambda: 0
d_lambda: 1.0
g_lambda: 1.0
pixel_loss: l1
output_dir: output
exp_name: mnist_ae_baseline_new
num_features: 10
root_dset: data