use_bbox: true
continue_checkpoint: false
no_scheduler: true
img_classifier: output/cub_img_classifier_small/img_classifier.pt
add_real_cls_vec: false
force_hardcode: false
only_recon: true
use_resnet_encoder: false
batch_size: 32
epochs: 500
extra_layers: 2
lr: 0.000001
recon_lambda: 1.0
recon_zero_lambda: 0
cls_lambda: 0
cls_zero_lambda: 0
kl_lambda: 0
sparcity_lambda: 0
force_dis_lambda: 0
output_dir: output
exp_name: cub_ae_824_only_recon
num_features: 824
root_dset: /local/scratch/cv_datasets/CUB_200_2011/