continue_checkpoint: false
no_scheduler: true
img_classifier: output/mnist_classifier_pretrain_resnet_rotation/img_classifier.pt
add_real_cls_vec: false
force_hardcode: true
only_recon: false
add_gan: false
use_patch_gan_dis: true
apply_rotation: false
batch_size: 1024
epochs: 100
extra_layers: 0
lr: 0.0002
recon_lambda: 1.0
recon_zero_lambda: 0
cls_lambda: 0.1
cls_zero_lambda: 0
kl_lambda: 0.001
swap_lambda: 0.1
img_size: 32
depth: 4
n_disc_layers: 3
gamma: 1.0
sparcity_lambda: 0
force_dis_lambda: 1.0
d_lambda: 1.0
g_lambda: 1.0
pixel_loss: l1
output_dir: output
exp_name: mnist_ae_nogan_rubric_fhc_class_swap
num_features: 64
root_dset: data